type Brew {
  author: String!
  batchSize: Float
  boilSize: Float!
  boilTime: Int!
  efficiency: Int!
  fermentables: [String]
  fermentableAmounts: [Float]
  ibus: Float!
  image: String!
  method: Int!
  name: String!
  notes: String!
  og: Float!
  srm: Float!
  hex: String!
  style: String!
  hops: [String]
  hopTypes: [Int]
  hopTimes: [Int]
  hopAmounts: [Float]
  others: [String]
  otherAmounts: [Float]
  otherTimes: [Time]
  yeast: [String]
}

type Query {
  LastThreeBrews: [Brew!]
}
